// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu_load.proto

#include "cpu_load.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace monitor {
namespace proto {
class CpuLoadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CpuLoad> _instance;
} _CpuLoad_default_instance_;
}  // namespace proto
}  // namespace monitor
static void InitDefaultsscc_info_CpuLoad_cpu_5fload_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_CpuLoad_default_instance_;
    new (ptr) ::monitor::proto::CpuLoad();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuLoad_cpu_5fload_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CpuLoad_cpu_5fload_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cpu_5fload_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cpu_5fload_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cpu_5fload_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cpu_5fload_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_1_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_3_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_15_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::monitor::proto::CpuLoad)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_CpuLoad_default_instance_),
};

const char descriptor_table_protodef_cpu_5fload_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016cpu_load.proto\022\rmonitor.proto\"F\n\007CpuLo"
  "ad\022\022\n\nload_avg_1\030\001 \001(\002\022\022\n\nload_avg_3\030\002 \001"
  "(\002\022\023\n\013load_avg_15\030\003 \001(\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cpu_5fload_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_cpu_5fload_2eproto_sccs[1] = {
  &scc_info_CpuLoad_cpu_5fload_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cpu_5fload_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cpu_5fload_2eproto = {
  false, false, descriptor_table_protodef_cpu_5fload_2eproto, "cpu_load.proto", 111,
  &descriptor_table_cpu_5fload_2eproto_once, descriptor_table_cpu_5fload_2eproto_sccs, descriptor_table_cpu_5fload_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_cpu_5fload_2eproto::offsets,
  file_level_metadata_cpu_5fload_2eproto, 1, file_level_enum_descriptors_cpu_5fload_2eproto, file_level_service_descriptors_cpu_5fload_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cpu_5fload_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_cpu_5fload_2eproto)), true);
namespace monitor {
namespace proto {

// ===================================================================

class CpuLoad::_Internal {
 public:
};

CpuLoad::CpuLoad(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:monitor.proto.CpuLoad)
}
CpuLoad::CpuLoad(const CpuLoad& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&load_avg_1_, &from.load_avg_1_,
    static_cast<size_t>(reinterpret_cast<char*>(&load_avg_15_) -
    reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
  // @@protoc_insertion_point(copy_constructor:monitor.proto.CpuLoad)
}

void CpuLoad::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&load_avg_1_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&load_avg_15_) -
      reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
}

CpuLoad::~CpuLoad() {
  // @@protoc_insertion_point(destructor:monitor.proto.CpuLoad)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CpuLoad::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CpuLoad::ArenaDtor(void* object) {
  CpuLoad* _this = reinterpret_cast< CpuLoad* >(object);
  (void)_this;
}
void CpuLoad::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CpuLoad::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CpuLoad& CpuLoad::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CpuLoad_cpu_5fload_2eproto.base);
  return *internal_default_instance();
}


void CpuLoad::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.CpuLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&load_avg_1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&load_avg_15_) -
      reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CpuLoad::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float load_avg_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          load_avg_1_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float load_avg_3 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          load_avg_3_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float load_avg_15 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          load_avg_15_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CpuLoad::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.CpuLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float load_avg_1 = 1;
  if (!(this->load_avg_1() <= 0 && this->load_avg_1() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_load_avg_1(), target);
  }

  // float load_avg_3 = 2;
  if (!(this->load_avg_3() <= 0 && this->load_avg_3() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_load_avg_3(), target);
  }

  // float load_avg_15 = 3;
  if (!(this->load_avg_15() <= 0 && this->load_avg_15() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_load_avg_15(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.CpuLoad)
  return target;
}

size_t CpuLoad::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.CpuLoad)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float load_avg_1 = 1;
  if (!(this->load_avg_1() <= 0 && this->load_avg_1() >= 0)) {
    total_size += 1 + 4;
  }

  // float load_avg_3 = 2;
  if (!(this->load_avg_3() <= 0 && this->load_avg_3() >= 0)) {
    total_size += 1 + 4;
  }

  // float load_avg_15 = 3;
  if (!(this->load_avg_15() <= 0 && this->load_avg_15() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CpuLoad::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.CpuLoad)
  GOOGLE_DCHECK_NE(&from, this);
  const CpuLoad* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CpuLoad>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.CpuLoad)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.CpuLoad)
    MergeFrom(*source);
  }
}

void CpuLoad::MergeFrom(const CpuLoad& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.CpuLoad)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.load_avg_1() <= 0 && from.load_avg_1() >= 0)) {
    _internal_set_load_avg_1(from._internal_load_avg_1());
  }
  if (!(from.load_avg_3() <= 0 && from.load_avg_3() >= 0)) {
    _internal_set_load_avg_3(from._internal_load_avg_3());
  }
  if (!(from.load_avg_15() <= 0 && from.load_avg_15() >= 0)) {
    _internal_set_load_avg_15(from._internal_load_avg_15());
  }
}

void CpuLoad::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.CpuLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CpuLoad::CopyFrom(const CpuLoad& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.CpuLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CpuLoad::IsInitialized() const {
  return true;
}

void CpuLoad::InternalSwap(CpuLoad* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CpuLoad, load_avg_15_)
      + sizeof(CpuLoad::load_avg_15_)
      - PROTOBUF_FIELD_OFFSET(CpuLoad, load_avg_1_)>(
          reinterpret_cast<char*>(&load_avg_1_),
          reinterpret_cast<char*>(&other->load_avg_1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CpuLoad::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace monitor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::monitor::proto::CpuLoad* Arena::CreateMaybeMessage< ::monitor::proto::CpuLoad >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitor::proto::CpuLoad >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
